networks:
  default:
    external:
      name: roboshop
voulumes:
  - mongodb
  - mysql
  - redis
  - rabbitmq
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongodb:1.0.0
    container_name: mongodb
    volumes:
      source: mongodb
      target: 
      type: volume
    # networks:
    # - roboshop
  catalogue:
    image:  catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  web:
    image:  web:1.0.0
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment
  redis:
    image: redis
    container_name: redis
    volumes:
      source: redis
      target: 
      type: volume

  cart: 
    image: cart:1.0.0
    container_name: cart
    depends_on:
    - catalogue
    - redis
  user:
    image:  user:1.0.0
    container_name: user
    depends_on:
    - mongodb
    - redis
  mysql:
    image:  mysql:1.0.0
    container_name: mysql
    volumes:
      source: mongodb
      target: 
      type: volume
  shipping:
    image:  shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      source: mongodb
      target: 
      type: volume

  payment:
    image: payment:1.0.0
    container_name: payment
    depends_on:
    - rabbitmq
    - user
    - cart
  


